# Generated by Django 4.2.6 on 2023-10-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.IntegerField(),
        ),
    ]
