# Generated by Django 4.2.6 on 2023-10-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='is_balance_sheet',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance_type',
            field=models.CharField(blank=True, choices=[('debe', 'Debe'), ('haber', 'Haber')], max_length=6),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=6),
        ),
    ]
