# Generated by Django 4.2.6 on 2023-10-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_ledger', '0002_ledger_is_balance_sheet_alter_account_balance_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='sum_of_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='account',
            name='sum_of_debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance_type',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(max_length=6),
        ),
    ]
