# Generated by Django 4.2.6 on 2023-10-25 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_ledger', '0003_account_sum_of_credit_account_sum_of_debit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='sum_of_credit',
        ),
        migrations.RemoveField(
            model_name='account',
            name='sum_of_debit',
        ),
    ]
