# Generated by Django 4.2.6 on 2023-10-23 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.IntegerField()),
                ('stock_unitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_date', models.DateField()),
                ('move_description', models.CharField(max_length=255)),
                ('move_type', models.CharField(max_length=10)),
                ('move_quantity', models.IntegerField()),
                ('move_unitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('move_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stock')),
            ],
        ),
    ]
