# Generated by Django 4.2.6 on 2023-10-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='move_description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
