# Generated by Django 4.2.6 on 2023-10-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_move_move_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_unitPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
