# Generated by Django 4.2.6 on 2023-10-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_stock_stock_price_alter_stock_stock_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_unitPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
