# Generated by Django 4.2.6 on 2023-10-24 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_stock_stock_price_alter_stock_stock_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_name',
            field=models.CharField(default='Existencias', max_length=255),
        ),
    ]
