# Generated by Django 4.2.1 on 2023-10-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stock_stock_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='stock_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='move',
            name='stock_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='move',
            name='stock_unitPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
